import '@/styles/globals.scss';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { HeaderFeature } from '@/features/HeaderFeature';
import { getClassList } from '@/utils/getClassList';

const golosText = localFont({
    src: '../fonts/GolosText.woff2',
    variable: '--font-golos-test',
});

/**
 * Метаданные для корневого макета
 */
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

/**
 * Корневой макет приложения
 */
const RootLayout: React.FC<React.PropsWithChildren> = (props) => {
    const { children } = props;
    const classList = getClassList(golosText.variable);

    return (
        <html lang="ru">
            <body className={classList}>
                <HeaderFeature />
                <main>{children}</main>
            </body>
        </html>
    );
};

export default RootLayout;
